spring:
  application:
    name: spring-cloud-eureka-server

# Server Config
server:
  port: 8761

# Eureka Server Config
eureka:
  instance:
     hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false