server:
  port: 8002
spring:
  application:
    name: TASK-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/task_service
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
