server:
  port: 8000

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**, /api/users/**, /users/**

        - id: TASK-SERVICE
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/api/tasks/**, /tasks/**

        - id: SUBMISSION-SERVICE
          uri: lb://SUBMISSION-SERVICE
          predicates:
            - Path=/api/submissions/**, /submissions/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials RETAIN_FIRST
        - DedupeResponseHeader=Access-Control-Allow-Origin RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origin-patterns:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            maxAge: 3600
            allow-credentials: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}