server:
  port: 8000
spring:
  application:
    name: GATEWAY-SERVICE

# eureka client config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
